language: haskell-multi-ghc

env:
  - GHCVER=7.8.4 CABALVER=1.18
  - GHCVER=7.8.4 CABALVER=1.18 STACKAGESNAPSHOT=lts-2.22
  - GHCVER=7.10.2 CABALVER=1.22
  - GHCVER=7.10.2 CABALVER=1.22 STACKAGESNAPSHOT=lts-3.22 PEDANTIC=YES
  - GHCVER=7.10.3 CABALVER=1.22
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-4.2 PEDANTIC=YES
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-5.11 PEDANTIC=YES
  - GHCVER=head CABALVER=1.22

matrix:
  fast_finish: true
  allow_failures:
    - env: GHCVER=head CABALVER=1.22

branches:
  only:
    - master

git:
  submodules: false
