name: ansi-pretty
version: 0.1.0.0
synopsis: AnsiPretty for ansi-wl-pprint
description: |
  'AnsiPretty' type class, more colorful than 'Pretty'.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-ansi-pretty
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - aeson                 >=0.8   && <0.11
  - ansi-wl-pprint        >=0.6   && <0.7
  - array                 >=0.5   && <0.6
  - base                  >=4.7   && <4.9
  - bytestring            >=0.10  && <0.11
  - containers            >=0.5   && <0.6
  - generics-sop          >=0.1   && <0.3
  - nats                  >=1     && <1.1
  - scientific            >=0.3   && <0.4
  - semigroups            >=0.16  && <0.18
  - tagged                >=0.7   && <0.9
  - text                  >=1.2   && <1.3
  - time                  >=1.4   && <1.6
  - unordered-containers  >=0.2   && <0.3
  - vector                >=0.10  && <0.12

library:
  source-dirs: src
