name: ansi-pretty
version: 0.1.0.0
synopsis: AnsiPretty for ansi-wl-pprint
description: |
  'AnsiPretty' type class, more colorful than 'Pretty'.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-ansi-pretty
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  >=4.7   && <4.9
  - aeson                 >=0.8   && <0.10
  - ansi-wl-pprint        >=0.6   && <0.7
  - generics-sop          >=0.1   && <0.2
  - semigroups            >=0.16  && <0.18
  - tagged                >=0.7   && <0.9
  - time                  >=1.4   && <1.6
  - text                  >=1.2   && <1.3

library:
  source-dirs: src
